// 0: "https://avatars.githubusercontent.com/u/52450973?v=4"
// 1: "A crypto influencer"
// 2: "satyasandeep786@gmail.com"
// 3: "https://satyasandeep.in"
// 4: "https://www.linkedin.com/in/satyasandeep/"
// 5: ""
// 6: "https://twitter.com/satyasandeep76"
// description: "A crypto influencer"
// emailId: "satyasandeep786@gmail.com"
// instagram: ""
// linkedIn: "https://www.linkedin.com/in/satyasandeep/"
// photo: "https://avatars.githubusercontent.com/u/52450973?v=4"
// twitter: "https://twitter.com/satyasandeep76"
// website: "https://satyasandeep.in"
